export const asciiTable = [
    ['NUL', '\\0, Null Character'],
    ['SOH', 'Start of Heading'],
    ['STX', 'Start of Text'],
    ['ETX', 'End of Text'],
    ['EOT', 'End of Transmission'],
    ['ENQ', 'Enquiry'],
    ['ACK', 'Acknowledge'],
    ['BEL', '\\a, Bell'],
    ['BS', '\\b, Backspace'],
    ['HT', '\\t, Horizontal Tab'],
    ['LF', '\\n, Line Feed, New Line'],
    ['VT', '\\v, Vertical Tab'],
    ['FF', '\\f, Form Feed, New Page'],
    ['CR', '\\r, Carriage Return'],
    ['SO', 'Shift Out'],
    ['SI', 'Shift In'],
    ['DLE', 'Data Link Escape'],
    ['DC1', 'Device Control 1'],
    ['DC2', 'Device Control 2'],
    ['DC3', 'Device Control 3'],
    ['DC4', 'Device Control 4'],
    ['NAK', 'Negative Acknowledge'],
    ['SYN', 'Synchronous Idle'],
    ['ETB', 'End of Trans. Block'],
    ['CAN', 'Cancel'],
    ['EM', 'End of Medium'],
    ['SUB', 'Substitute'],
    ['ESC', 'Escape'],
    ['FS', 'File Separator'],
    ['GS', 'Group Separator'],
    ['RS', 'Record Separator'],
    ['US', 'Unit Separator'],
    ['SPACE', 'Space'],
    ['!', 'Exclamation Mark'],
    ['"', 'Double Quotes'],
    ['#', 'Number Sign'],
    ['$', 'Dollar'],
    ['%', 'Percent Sign'],
    ['&', 'Ampersand'],
    ["'", 'Single Quote'],
    ['(', 'Open Parenthesis (Bracket)'],
    [')', 'Close Parenthesis (Bracket)'],
    ['*', 'Asterisk'],
    ['+', 'Plus'],
    [',', 'Comma'],
    ['-', 'Hyphen-minus'],
    ['.', 'Period, Dot'],
    ['/', 'Slash or divide'],
    ['0', 'Number Zero'],
    ['1', 'Number One'],
    ['2', 'Number Two'],
    ['3', 'Number Three'],
    ['4', 'Number Four'],
    ['5', 'Number Five'],
    ['6', 'Number Six'],
    ['7', 'Number Seven'],
    ['8', 'Number Eight'],
    ['9', 'Number Nine'],
    [':', 'Colon'],
    [';', 'Semicolon'],
    ['<', 'Less Than (Open Angled Bracket)'],
    ['=', 'Equals'],
    ['>', 'Greater Than (Close Angled Bracket)'],
    ['?', 'Question Mark'],
    ['@', 'At Sign'],
    ['A', 'Uppercase A'],
    ['B', 'Uppercase B'],
    ['C', 'Uppercase C'],
    ['D', 'Uppercase D'],
    ['E', 'Uppercase E'],
    ['F', 'Uppercase F'],
    ['G', 'Uppercase G'],
    ['H', 'Uppercase H'],
    ['I', 'Uppercase I'],
    ['J', 'Uppercase J'],
    ['K', 'Uppercase K'],
    ['L', 'Uppercase L'],
    ['M', 'Uppercase M'],
    ['N', 'Uppercase N'],
    ['O', 'Uppercase O'],
    ['P', 'Uppercase P'],
    ['Q', 'Uppercase Q'],
    ['R', 'Uppercase R'],
    ['S', 'Uppercase S'],
    ['T', 'Uppercase T'],
    ['U', 'Uppercase U'],
    ['V', 'Uppercase V'],
    ['W', 'Uppercase W'],
    ['X', 'Uppercase X'],
    ['Y', 'Uppercase Y'],
    ['Z', 'Uppercase Z'],
    ['[', 'Opening Square Bracket'],
    ['\\', '\\\\, Backslash'],
    [']', 'Closing Square Bracket'],
    ['^', 'Caret'],
    ['_', 'Underscore'],
    ['`', 'Grave Accent, Backtick or Backquote'],
    ['a', 'Lowercase a'],
    ['b', 'Lowercase b'],
    ['c', 'Lowercase c'],
    ['d', 'Lowercase d'],
    ['e', 'Lowercase e'],
    ['f', 'Lowercase f'],
    ['g', 'Lowercase g'],
    ['h', 'Lowercase h'],
    ['i', 'Lowercase i'],
    ['j', 'Lowercase j'],
    ['k', 'Lowercase k'],
    ['l', 'Lowercase l'],
    ['m', 'Lowercase m'],
    ['n', 'Lowercase n'],
    ['o', 'Lowercase o'],
    ['p', 'Lowercase p'],
    ['q', 'Lowercase q'],
    ['r', 'Lowercase r'],
    ['s', 'Lowercase s'],
    ['t', 'Lowercase t'],
    ['u', 'Lowercase u'],
    ['v', 'Lowercase v'],
    ['w', 'Lowercase w'],
    ['x', 'Lowercase x'],
    ['y', 'Lowercase y'],
    ['z', 'Lowercase z'],
    ['{', 'Opening Brace'],
    ['|', 'Vertical Bar'],
    ['}', 'Closing Brace'],
    ['~', 'Equivalency Sign, Tilde'],
    ['DEL', 'Delete'],
];

export const codeMap: { [char: string]: number } = {
    NUL: 0,
    SOH: 1,
    STX: 2,
    ETX: 3,
    EOT: 4,
    ENQ: 5,
    ACK: 6,
    BEL: 7,
    BS: 8,
    HT: 9,
    LF: 10,
    VT: 11,
    FF: 12,
    CR: 13,
    SO: 14,
    SI: 15,
    DLE: 16,
    DC1: 17,
    DC2: 18,
    DC3: 19,
    DC4: 20,
    NAK: 21,
    SYN: 22,
    ETB: 23,
    CAN: 24,
    EM: 25,
    SUB: 26,
    ESC: 27,
    FS: 28,
    GS: 29,
    RS: 30,
    US: 31,
    SPACE: 32,
    '!': 33,
    '"': 34,
    '#': 35,
    $: 36,
    '%': 37,
    '&': 38,
    "'": 39,
    '(': 40,
    ')': 41,
    '*': 42,
    '+': 43,
    ',': 44,
    '-': 45,
    '.': 46,
    '/': 47,
    '0': 48,
    '1': 49,
    '2': 50,
    '3': 51,
    '4': 52,
    '5': 53,
    '6': 54,
    '7': 55,
    '8': 56,
    '9': 57,
    ':': 58,
    ';': 59,
    '<': 60,
    '=': 61,
    '>': 62,
    '?': 63,
    '@': 64,
    A: 65,
    B: 66,
    C: 67,
    D: 68,
    E: 69,
    F: 70,
    G: 71,
    H: 72,
    I: 73,
    J: 74,
    K: 75,
    L: 76,
    M: 77,
    N: 78,
    O: 79,
    P: 80,
    Q: 81,
    R: 82,
    S: 83,
    T: 84,
    U: 85,
    V: 86,
    W: 87,
    X: 88,
    Y: 89,
    Z: 90,
    '[': 91,
    '\\': 92,
    ']': 93,
    '^': 94,
    _: 95,
    '`': 96,
    a: 97,
    b: 98,
    c: 99,
    d: 100,
    e: 101,
    f: 102,
    g: 103,
    h: 104,
    i: 105,
    j: 106,
    k: 107,
    l: 108,
    m: 109,
    n: 110,
    o: 111,
    p: 112,
    q: 113,
    r: 114,
    s: 115,
    t: 116,
    u: 117,
    v: 118,
    w: 119,
    x: 120,
    y: 121,
    z: 122,
    '{': 123,
    '|': 124,
    '}': 125,
    '~': 126,
    DEL: 127,
};
